### ISSUE TITLE
Unraid download error 

### ISSUE THREAD

**Issue by mxioi** [Ratomas/CreateA-B#2]
Hi, I'm having an issue where the docker file can't be found. any suggestion on a resolution?

![Screenshot 2024-01-12 065815](https://github.com/Ratomas/CreateA-B/assets/101600065/857e8437-1663-4a24-ad2b-0e7ffe1aceb7)

**Comment by Ratomas** [comment]
Ok I am fixing this issue should have the fix out shortly.

**Comment by Ratomas** [comment]
Ok I messed up and left a reference from another modpack in the DockerFile and the launch.sh. I removed the reference and put the call to the server-1.3.jar in its place. Should work now if you pull the image again.
